### ISSUE TITLE
How to mix with AJAX calls?

### ISSUE THREAD

**Issue by ppazos** [mistic100/Bootstrap-Confirmation#131]
I have a link that is actually handled by JS and fires an AJAX call. After adding the confirmation, the AJAX call is executed, but also the link fires a normal request (not handled by AJAX), so my server is receiving two requests.

How can I prevent the confirmation to fire the normal request when the request is really handled by AJAX?

**Comment by mistic100** [comment]
if the processing must exclusively be handled in AJAX, do not use a link a[href] in the first place

**Comment by ppazos** [comment]
@mistic100 why not? it's very common to catch the click event on links and do an e.preventDefault()

Either way, will it work with a button?

**Comment by mistic100** [comment]
With a button it should work, as soon as there is no default action on the button.  
the thing is there is no access to the original event from the plugin https://github.com/mistic100/Bootstrap-Confirmation/blob/master/src/confirmation.js#L379-L381 so you cannot use preventDefault()

Another solution is to use custom buttons configured with "cancel"


```
element.confirmation({
  buttons: [
    { label: 'Cancel', cancel: true },
    { label: 'Send', cancel: true, onClick: doSend }
  ],
});
```

because all buttons are marked "cancel" none of them will trigger the default action
